### ISSUE TITLE
No instructions on how to run the code

### ISSUE THREAD

**Issue by pdulak** [siddheshkothadi/code-type#8]
As a developer who is not coding in JavaScript on daily basis, I find it hard to run the application. I cloned the repo and what's next?

**Comment by siddheshkothadi** [comment]
Thank you @pdulak. 
I've added the getting started part in the <a href="https://github.com/siddheshkothadi/code-type/blob/main/README.md#getting-started">README.md</a> file. Please do let me know if you are facing any other issues
